// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

import 'dart:convert';

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import '../third_party/dion_runtime/datastructs.dart';
import '../third_party/dion_runtime/permission.dart';
import '../third_party/dion_runtime/settings.dart';
import 'cancel.dart';
import 'client.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// Rust type: RustOpaqueNom<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<ProxyExtension>>
abstract class ProxyExtension implements RustOpaqueInterface {
  Future<EntryList> browse({required int page, CancelToken? token});

  Future<EntryDetailedResult> detail(
      {required String entryid,
      required Map<String, Setting> settings,
      CancelToken? token});

  Future<bool> fromurl({required String url, CancelToken? token});

  Future<ExtensionData> getExtensionData();

  Future<List<Permission>> getPermissions();

  Future<Setting> getSetting({required String id, required SettingKind kind});

  Future<List<String>> getSettingIds({required SettingKind kind});

  Future<Map<String, Setting>> getSettings({required SettingKind kind});

  Future<bool> hasPermission({required Permission permission});

  Future<bool> isEnabled();

  Future<EntryDetailedResult> mapEntry(
      {required EntryDetailed entry,
      required Map<String, Setting> settings,
      CancelToken? token});

  Future<SourceResult> mapSource(
      {required Source source,
      required Map<String, Setting> settings,
      CancelToken? token});

  Future<void> mergeSettingDefinition(
      {required String id,
      required SettingKind kind,
      required Setting definition});

  Future<void> onEntryActivity(
      {required EntryActivity activity,
      required EntryDetailed entry,
      required Map<String, Setting> settings,
      CancelToken? token});

  Future<void> reload();

  Future<void> removePermission({required Permission permission});

  Future<void> removeSetting({required String id, required SettingKind kind});

  Future<EntryList> search(
      {required int page, required String filter, CancelToken? token});

  Future<void> setEnabled({required bool enabled});

  Future<void> setSetting(
      {required String id,
      required SettingKind kind,
      required SettingValue value});

  Future<SourceResult> source(
      {required String epid,
      required Map<String, Setting> settings,
      CancelToken? token});
}

// Rust type: RustOpaqueNom<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<ProxyExtensionManager>>
abstract class ProxyExtensionManager implements RustOpaqueInterface {
  Future<List<ProxyExtension>> getExtensions();

  Future<ExtensionRepo> getRepo({required String url});

  static Future<ProxyExtensionManager> initDion(
          {required ManagerClient client}) =>
      RustLib.instance.api
          .crateApiExtensionProxyExtensionManagerInitDion(client: client);

  Future<ProxyExtension> install({required RemoteExtension location});

  Future<ProxyExtension> installSingle({required String url});

  Future<void> uninstall({required ProxyExtension ext});
}
