# https://taskfile.dev

version: "3"

tasks:
  test:
    cmds:
      - bun run ./script/index.js build test
  format:
    cmds:
      - bun run ./script/index.js format lint
  clean:
    cmds:
      - bun run ./script/index.js clean
