# https://taskfile.dev

version: '3'

includes:
  platform_dependent: 
    taskfile: ./Taskfile_{{OS}}.yml
    optional: true
    flatten: true


tasks:
  test:
      cmds:
        - cd rust/core && cargo test
        - task: platform_dependent:shexec
          vars: { CMD: 'cd dart/rdion_runtime/example && flutter test integration_test/simple_test.dart' }
  generate:
      cmds:
        - task: platform_dependent:shexec
          vars: { CMD: 'cd dart/rdion_runtime && flutter pub run build_runner clean && flutter_rust_bridge_codegen generate' }