//{"id":"html","name":"html","url":"www.example.com","icon":"www.example.com/icon.png","lang":[],"nsfw":false,"media_type":["Book"],"extension_type":[],"version":"1.0.0","license":"ISC","api_version":"*","repo":"string"}
import{fetch as c}from"network";import{getSetting as S}from"setting";class g{async onEvent(n){switch(n.type){case"Action":return;case"FeedUpdate":return{type:n.type,customui:[],hasnext:null,length:null};case"SwapContent":return{type:n.type,customui:{type:"Text",text:"asd"}}}}async mapSource(n,t,r){return{source:n,settings:r}}async mapEntry(n,t){return{entry:n,settings:t}}async onEntryActivity(n,t,r){}async browse(n){let t=await y();return{content:(await c(`${t}/getEntries`)).json}}async search(n,t){let r=await y();return{content:(await c(`${r}/getEntries`)).json}}async handleUrl(n){return!0}async detail(n,t){let r=await y();return{entry:(await c(`${r}/getEntry`)).json,settings:t}}async source(n,t){let r=await y();return{source:(await c(`${r}/getSource`)).json,settings:t}}}async function y(){let n=await S("testdataserver","Extension"),t=n.value.data;if(n.value.type!=="String")throw Error("Failed to get Server");if(t.endsWith("/"))return t.substring(0,t.length-1);return t}function u(n,t="Extension error"){if(!n)throw new Error(`Assert failed: ${t}`)}function e(n,t,r="Assert"){let[o,i]=d(n,t);if(!o)throw new Error(` ${r} failed: ${i}`)}function d(n,t,r=""){if(typeof n!==typeof t)return[!1,`Failed at ${r}. Expected ${typeof n} but got ${typeof t}`];if(Array.isArray(n)&&Array.isArray(t)){if(n.length!==t.length)return[!1,`Failed at ${r}. Expected array of length ${n.length} but got length ${t.length} 
expected: ${JSON.stringify(n)}
got: ${JSON.stringify(t)}`];for(let o=0;o<n.length;o++){let[i,s]=d(n[o],t[o],`${r}[${o}]`);if(!i)return[!1,s]}}else if(n instanceof Object&&t instanceof Object)for(let o of Object.keys(n)){let[i,s]=d(n[o],t[o],`${r}.${o}`);if(!i)return[!1,s]}else if(n!==t)return[!1,`Failed at ${r}. Expected ${n} but got ${t} 
expected: ${JSON.stringify(n)}
got: ${JSON.stringify(t)}`];return[!0,""]}import{parseHtml as E,parseHtmlFragment as f}from"parse";function $(){let t=E('<html><body><div attr="value">some text</div><div>some other text</div></body></html>'),r=new CSSSelector("div"),o=t.select(r),i=o.first;u(i!==void 0,"div select not working"),e("some text",i.text,"parse_html not working"),e("body",i.parent?.name,"parse_html not working"),e("div",i.name,"parse_html not working"),e("value",i.attr("attr"),"parse_html not working"),e(2,o.length,"parse_html not working"),e(`some text
some other text`,o.map((s)=>s.text).join(`
`),"parse_html not working")}function a(){let t=f('<div attr="value"> some text <span>some other text</span></div>').children.get(0);u(t!==void 0,"div select not working"),e("div",t.name,"Element.name not working"),e("some text some other text",t.text.trim(),"Element.text not working"),e("some other text",t.select(new CSSSelector("span")).text,"Element.select not working"),e("value",t.attr("attr"),"Element.attr not working"),e("some other text",t.children.first?.text,"Element.children not working")}function v(){let r=f(`
    <ul>
    <li attr="1">one</li>
    <li attr="2" class="test">two</li>
    <li attr="3">three</li>
    </ul>`).select(new CSSSelector("ul")).first?.children;u(r!==void 0,"Couldnt find ul"),e(3,r.length,"Wrong Number of children"),e(["1","2","3"],r.attr("attr"),"ElementArray.attr not working"),e("2",r.select(new CSSSelector("li.test")).first?.attr("attr"),"ElementArray.select not working"),e("2",r.get(1)?.attr("attr"),"ElementArray.get not working"),e(`one
two
three`,r.map((o)=>o.text).join(`
`),"ElementArray.map not working"),e(["1","3"],r.filter((o)=>o.attr("attr")!=="2").attr("attr"),"ElementArray.filter not working"),e("one",r.first?.text,"ElementArray.first not working"),e(3,r.length,"ElementArray.length not working")}class b extends g{async load(){$(),a(),v()}}export{b as default};
