// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.4.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/simple.dart';
import 'dart:async';
import 'dart:convert';
import 'dart:ffi' as ffi;
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_io.dart';
import 'third_party/dion_runtime/datastructs.dart';
import 'third_party/dion_runtime/jsextension.dart';
import 'third_party/dion_runtime/permission.dart';
import 'third_party/dion_runtime/settings.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  CrossPlatformFinalizerArg
      get rust_arc_decrement_strong_count_CancelTokenPtr => wire
          ._rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCancelTokenPtr;

  CrossPlatformFinalizerArg
      get rust_arc_decrement_strong_count_ExtensionManagerProxyPtr => wire
          ._rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerExtensionManagerProxyPtr;

  CrossPlatformFinalizerArg
      get rust_arc_decrement_strong_count_ExtensionProxyPtr => wire
          ._rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerExtensionProxyPtr;

  CrossPlatformFinalizerArg get rust_arc_decrement_strong_count_QueueStorePtr =>
      wire._rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerQueueStorePtr;

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw);

  @protected
  CancelToken
      dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCancelToken(
          dynamic raw);

  @protected
  ExtensionManagerProxy
      dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerExtensionManagerProxy(
          dynamic raw);

  @protected
  ExtensionProxy
      dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerExtensionProxy(
          dynamic raw);

  @protected
  QueueStore
      dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerQueueStore(
          dynamic raw);

  @protected
  ExtensionManagerProxy
      dco_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerExtensionManagerProxy(
          dynamic raw);

  @protected
  ExtensionManagerProxy
      dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerExtensionManagerProxy(
          dynamic raw);

  @protected
  ExtensionProxy
      dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerExtensionProxy(
          dynamic raw);

  @protected
  Map<String, String> dco_decode_Map_String_String(dynamic raw);

  @protected
  CancelToken
      dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCancelToken(
          dynamic raw);

  @protected
  ExtensionManagerProxy
      dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerExtensionManagerProxy(
          dynamic raw);

  @protected
  ExtensionProxy
      dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerExtensionProxy(
          dynamic raw);

  @protected
  QueueStore
      dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerQueueStore(
          dynamic raw);

  @protected
  RustStreamSink<PermissionRequest>
      dco_decode_StreamSink_permission_request_Dco(dynamic raw);

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  CancelToken
      dco_decode_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCancelToken(
          dynamic raw);

  @protected
  bool dco_decode_box_autoadd_bool(dynamic raw);

  @protected
  DataSource dco_decode_box_autoadd_data_source(dynamic raw);

  @protected
  Entry dco_decode_box_autoadd_entry(dynamic raw);

  @protected
  double dco_decode_box_autoadd_f_32(dynamic raw);

  @protected
  PlatformInt64 dco_decode_box_autoadd_i_64(dynamic raw);

  @protected
  LinkSource dco_decode_box_autoadd_link_source(dynamic raw);

  @protected
  Permission dco_decode_box_autoadd_permission(dynamic raw);

  @protected
  SettingUI dco_decode_box_autoadd_setting_ui(dynamic raw);

  @protected
  Settingvalue dco_decode_box_autoadd_settingvalue(dynamic raw);

  @protected
  DataSource dco_decode_data_source(dynamic raw);

  @protected
  Entry dco_decode_entry(dynamic raw);

  @protected
  EntryDetailed dco_decode_entry_detailed(dynamic raw);

  @protected
  Episode dco_decode_episode(dynamic raw);

  @protected
  EpisodeList dco_decode_episode_list(dynamic raw);

  @protected
  ExtensionData dco_decode_extension_data(dynamic raw);

  @protected
  double dco_decode_f_32(dynamic raw);

  @protected
  double dco_decode_f_64(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw);

  @protected
  ImageListAudio dco_decode_image_list_audio(dynamic raw);

  @protected
  LinkSource dco_decode_link_source(dynamic raw);

  @protected
  List<ExtensionProxy>
      dco_decode_list_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerExtensionProxy(
          dynamic raw);

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  List<Entry> dco_decode_list_entry(dynamic raw);

  @protected
  List<Episode> dco_decode_list_episode(dynamic raw);

  @protected
  List<EpisodeList> dco_decode_list_episode_list(dynamic raw);

  @protected
  List<ImageListAudio> dco_decode_list_image_list_audio(dynamic raw);

  @protected
  List<MediaType> dco_decode_list_media_type(dynamic raw);

  @protected
  List<Permission> dco_decode_list_permission(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<(String, String)> dco_decode_list_record_string_string(dynamic raw);

  @protected
  List<Subtitles> dco_decode_list_subtitles(dynamic raw);

  @protected
  MediaType dco_decode_media_type(dynamic raw);

  @protected
  Map<String, String>? dco_decode_opt_Map_String_String(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  CancelToken?
      dco_decode_opt_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCancelToken(
          dynamic raw);

  @protected
  bool? dco_decode_opt_box_autoadd_bool(dynamic raw);

  @protected
  Entry? dco_decode_opt_box_autoadd_entry(dynamic raw);

  @protected
  double? dco_decode_opt_box_autoadd_f_32(dynamic raw);

  @protected
  PlatformInt64? dco_decode_opt_box_autoadd_i_64(dynamic raw);

  @protected
  SettingUI? dco_decode_opt_box_autoadd_setting_ui(dynamic raw);

  @protected
  List<String>? dco_decode_opt_list_String(dynamic raw);

  @protected
  List<MediaType>? dco_decode_opt_list_media_type(dynamic raw);

  @protected
  Permission dco_decode_permission(dynamic raw);

  @protected
  PermissionRequest dco_decode_permission_request(dynamic raw);

  @protected
  (String, String) dco_decode_record_string_string(dynamic raw);

  @protected
  ReleaseStatus dco_decode_release_status(dynamic raw);

  @protected
  Setting dco_decode_setting(dynamic raw);

  @protected
  SettingUI dco_decode_setting_ui(dynamic raw);

  @protected
  Settingtype dco_decode_settingtype(dynamic raw);

  @protected
  Settingvalue dco_decode_settingvalue(dynamic raw);

  @protected
  Sort dco_decode_sort(dynamic raw);

  @protected
  Source dco_decode_source(dynamic raw);

  @protected
  Subtitles dco_decode_subtitles(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  BigInt dco_decode_usize(dynamic raw);

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer);

  @protected
  CancelToken
      sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCancelToken(
          SseDeserializer deserializer);

  @protected
  ExtensionManagerProxy
      sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerExtensionManagerProxy(
          SseDeserializer deserializer);

  @protected
  ExtensionProxy
      sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerExtensionProxy(
          SseDeserializer deserializer);

  @protected
  QueueStore
      sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerQueueStore(
          SseDeserializer deserializer);

  @protected
  ExtensionManagerProxy
      sse_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerExtensionManagerProxy(
          SseDeserializer deserializer);

  @protected
  ExtensionManagerProxy
      sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerExtensionManagerProxy(
          SseDeserializer deserializer);

  @protected
  ExtensionProxy
      sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerExtensionProxy(
          SseDeserializer deserializer);

  @protected
  Map<String, String> sse_decode_Map_String_String(
      SseDeserializer deserializer);

  @protected
  CancelToken
      sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCancelToken(
          SseDeserializer deserializer);

  @protected
  ExtensionManagerProxy
      sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerExtensionManagerProxy(
          SseDeserializer deserializer);

  @protected
  ExtensionProxy
      sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerExtensionProxy(
          SseDeserializer deserializer);

  @protected
  QueueStore
      sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerQueueStore(
          SseDeserializer deserializer);

  @protected
  RustStreamSink<PermissionRequest>
      sse_decode_StreamSink_permission_request_Dco(
          SseDeserializer deserializer);

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  CancelToken
      sse_decode_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCancelToken(
          SseDeserializer deserializer);

  @protected
  bool sse_decode_box_autoadd_bool(SseDeserializer deserializer);

  @protected
  DataSource sse_decode_box_autoadd_data_source(SseDeserializer deserializer);

  @protected
  Entry sse_decode_box_autoadd_entry(SseDeserializer deserializer);

  @protected
  double sse_decode_box_autoadd_f_32(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_box_autoadd_i_64(SseDeserializer deserializer);

  @protected
  LinkSource sse_decode_box_autoadd_link_source(SseDeserializer deserializer);

  @protected
  Permission sse_decode_box_autoadd_permission(SseDeserializer deserializer);

  @protected
  SettingUI sse_decode_box_autoadd_setting_ui(SseDeserializer deserializer);

  @protected
  Settingvalue sse_decode_box_autoadd_settingvalue(
      SseDeserializer deserializer);

  @protected
  DataSource sse_decode_data_source(SseDeserializer deserializer);

  @protected
  Entry sse_decode_entry(SseDeserializer deserializer);

  @protected
  EntryDetailed sse_decode_entry_detailed(SseDeserializer deserializer);

  @protected
  Episode sse_decode_episode(SseDeserializer deserializer);

  @protected
  EpisodeList sse_decode_episode_list(SseDeserializer deserializer);

  @protected
  ExtensionData sse_decode_extension_data(SseDeserializer deserializer);

  @protected
  double sse_decode_f_32(SseDeserializer deserializer);

  @protected
  double sse_decode_f_64(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer);

  @protected
  ImageListAudio sse_decode_image_list_audio(SseDeserializer deserializer);

  @protected
  LinkSource sse_decode_link_source(SseDeserializer deserializer);

  @protected
  List<ExtensionProxy>
      sse_decode_list_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerExtensionProxy(
          SseDeserializer deserializer);

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  List<Entry> sse_decode_list_entry(SseDeserializer deserializer);

  @protected
  List<Episode> sse_decode_list_episode(SseDeserializer deserializer);

  @protected
  List<EpisodeList> sse_decode_list_episode_list(SseDeserializer deserializer);

  @protected
  List<ImageListAudio> sse_decode_list_image_list_audio(
      SseDeserializer deserializer);

  @protected
  List<MediaType> sse_decode_list_media_type(SseDeserializer deserializer);

  @protected
  List<Permission> sse_decode_list_permission(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<(String, String)> sse_decode_list_record_string_string(
      SseDeserializer deserializer);

  @protected
  List<Subtitles> sse_decode_list_subtitles(SseDeserializer deserializer);

  @protected
  MediaType sse_decode_media_type(SseDeserializer deserializer);

  @protected
  Map<String, String>? sse_decode_opt_Map_String_String(
      SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  CancelToken?
      sse_decode_opt_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCancelToken(
          SseDeserializer deserializer);

  @protected
  bool? sse_decode_opt_box_autoadd_bool(SseDeserializer deserializer);

  @protected
  Entry? sse_decode_opt_box_autoadd_entry(SseDeserializer deserializer);

  @protected
  double? sse_decode_opt_box_autoadd_f_32(SseDeserializer deserializer);

  @protected
  PlatformInt64? sse_decode_opt_box_autoadd_i_64(SseDeserializer deserializer);

  @protected
  SettingUI? sse_decode_opt_box_autoadd_setting_ui(
      SseDeserializer deserializer);

  @protected
  List<String>? sse_decode_opt_list_String(SseDeserializer deserializer);

  @protected
  List<MediaType>? sse_decode_opt_list_media_type(SseDeserializer deserializer);

  @protected
  Permission sse_decode_permission(SseDeserializer deserializer);

  @protected
  PermissionRequest sse_decode_permission_request(SseDeserializer deserializer);

  @protected
  (String, String) sse_decode_record_string_string(
      SseDeserializer deserializer);

  @protected
  ReleaseStatus sse_decode_release_status(SseDeserializer deserializer);

  @protected
  Setting sse_decode_setting(SseDeserializer deserializer);

  @protected
  SettingUI sse_decode_setting_ui(SseDeserializer deserializer);

  @protected
  Settingtype sse_decode_settingtype(SseDeserializer deserializer);

  @protected
  Settingvalue sse_decode_settingvalue(SseDeserializer deserializer);

  @protected
  Sort sse_decode_sort(SseDeserializer deserializer);

  @protected
  Source sse_decode_source(SseDeserializer deserializer);

  @protected
  Subtitles sse_decode_subtitles(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer);

  @protected
  ffi.Pointer<wire_cst_list_prim_u_8_strict> cst_encode_AnyhowException(
      AnyhowException raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    throw UnimplementedError();
  }

  @protected
  ffi.Pointer<wire_cst_list_record_string_string> cst_encode_Map_String_String(
      Map<String, String> raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return cst_encode_list_record_string_string(
        raw.entries.map((e) => (e.key, e.value)).toList());
  }

  @protected
  ffi.Pointer<wire_cst_list_prim_u_8_strict>
      cst_encode_StreamSink_permission_request_Dco(
          RustStreamSink<PermissionRequest> raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return cst_encode_String(raw.setupAndSerialize(
        codec: DcoCodec(
      decodeSuccessData: dco_decode_permission_request,
      decodeErrorData: dco_decode_AnyhowException,
    )));
  }

  @protected
  ffi.Pointer<wire_cst_list_prim_u_8_strict> cst_encode_String(String raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return cst_encode_list_prim_u_8_strict(utf8.encoder.convert(raw));
  }

  @protected
  ffi.Pointer<ffi.UintPtr>
      cst_encode_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCancelToken(
          CancelToken raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return wire
        .cst_new_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCancelToken(
            cst_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCancelToken(
                raw));
  }

  @protected
  ffi.Pointer<ffi.Bool> cst_encode_box_autoadd_bool(bool raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return wire.cst_new_box_autoadd_bool(cst_encode_bool(raw));
  }

  @protected
  ffi.Pointer<wire_cst_data_source> cst_encode_box_autoadd_data_source(
      DataSource raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    final ptr = wire.cst_new_box_autoadd_data_source();
    cst_api_fill_to_wire_data_source(raw, ptr.ref);
    return ptr;
  }

  @protected
  ffi.Pointer<wire_cst_entry> cst_encode_box_autoadd_entry(Entry raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    final ptr = wire.cst_new_box_autoadd_entry();
    cst_api_fill_to_wire_entry(raw, ptr.ref);
    return ptr;
  }

  @protected
  ffi.Pointer<ffi.Float> cst_encode_box_autoadd_f_32(double raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return wire.cst_new_box_autoadd_f_32(cst_encode_f_32(raw));
  }

  @protected
  ffi.Pointer<ffi.Int64> cst_encode_box_autoadd_i_64(PlatformInt64 raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return wire.cst_new_box_autoadd_i_64(cst_encode_i_64(raw));
  }

  @protected
  ffi.Pointer<wire_cst_link_source> cst_encode_box_autoadd_link_source(
      LinkSource raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    final ptr = wire.cst_new_box_autoadd_link_source();
    cst_api_fill_to_wire_link_source(raw, ptr.ref);
    return ptr;
  }

  @protected
  ffi.Pointer<wire_cst_permission> cst_encode_box_autoadd_permission(
      Permission raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    final ptr = wire.cst_new_box_autoadd_permission();
    cst_api_fill_to_wire_permission(raw, ptr.ref);
    return ptr;
  }

  @protected
  ffi.Pointer<wire_cst_setting_ui> cst_encode_box_autoadd_setting_ui(
      SettingUI raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    final ptr = wire.cst_new_box_autoadd_setting_ui();
    cst_api_fill_to_wire_setting_ui(raw, ptr.ref);
    return ptr;
  }

  @protected
  ffi.Pointer<wire_cst_settingvalue> cst_encode_box_autoadd_settingvalue(
      Settingvalue raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    final ptr = wire.cst_new_box_autoadd_settingvalue();
    cst_api_fill_to_wire_settingvalue(raw, ptr.ref);
    return ptr;
  }

  @protected
  int cst_encode_i_64(PlatformInt64 raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw.toInt();
  }

  @protected
  ffi.Pointer<
          wire_cst_list_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerExtensionProxy>
      cst_encode_list_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerExtensionProxy(
          List<ExtensionProxy> raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    final ans = wire
        .cst_new_list_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerExtensionProxy(
            raw.length);
    for (var i = 0; i < raw.length; ++i) {
      ans.ref.ptr[i] =
          cst_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerExtensionProxy(
              raw[i]);
    }
    return ans;
  }

  @protected
  ffi.Pointer<wire_cst_list_String> cst_encode_list_String(List<String> raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    final ans = wire.cst_new_list_String(raw.length);
    for (var i = 0; i < raw.length; ++i) {
      ans.ref.ptr[i] = cst_encode_String(raw[i]);
    }
    return ans;
  }

  @protected
  ffi.Pointer<wire_cst_list_entry> cst_encode_list_entry(List<Entry> raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    final ans = wire.cst_new_list_entry(raw.length);
    for (var i = 0; i < raw.length; ++i) {
      cst_api_fill_to_wire_entry(raw[i], ans.ref.ptr[i]);
    }
    return ans;
  }

  @protected
  ffi.Pointer<wire_cst_list_episode> cst_encode_list_episode(
      List<Episode> raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    final ans = wire.cst_new_list_episode(raw.length);
    for (var i = 0; i < raw.length; ++i) {
      cst_api_fill_to_wire_episode(raw[i], ans.ref.ptr[i]);
    }
    return ans;
  }

  @protected
  ffi.Pointer<wire_cst_list_episode_list> cst_encode_list_episode_list(
      List<EpisodeList> raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    final ans = wire.cst_new_list_episode_list(raw.length);
    for (var i = 0; i < raw.length; ++i) {
      cst_api_fill_to_wire_episode_list(raw[i], ans.ref.ptr[i]);
    }
    return ans;
  }

  @protected
  ffi.Pointer<wire_cst_list_image_list_audio> cst_encode_list_image_list_audio(
      List<ImageListAudio> raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    final ans = wire.cst_new_list_image_list_audio(raw.length);
    for (var i = 0; i < raw.length; ++i) {
      cst_api_fill_to_wire_image_list_audio(raw[i], ans.ref.ptr[i]);
    }
    return ans;
  }

  @protected
  ffi.Pointer<wire_cst_list_media_type> cst_encode_list_media_type(
      List<MediaType> raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    final ans = wire.cst_new_list_media_type(raw.length);
    for (var i = 0; i < raw.length; ++i) {
      ans.ref.ptr[i] = cst_encode_media_type(raw[i]);
    }
    return ans;
  }

  @protected
  ffi.Pointer<wire_cst_list_permission> cst_encode_list_permission(
      List<Permission> raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    final ans = wire.cst_new_list_permission(raw.length);
    for (var i = 0; i < raw.length; ++i) {
      cst_api_fill_to_wire_permission(raw[i], ans.ref.ptr[i]);
    }
    return ans;
  }

  @protected
  ffi.Pointer<wire_cst_list_prim_u_8_strict> cst_encode_list_prim_u_8_strict(
      Uint8List raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    final ans = wire.cst_new_list_prim_u_8_strict(raw.length);
    ans.ref.ptr.asTypedList(raw.length).setAll(0, raw);
    return ans;
  }

  @protected
  ffi.Pointer<wire_cst_list_record_string_string>
      cst_encode_list_record_string_string(List<(String, String)> raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    final ans = wire.cst_new_list_record_string_string(raw.length);
    for (var i = 0; i < raw.length; ++i) {
      cst_api_fill_to_wire_record_string_string(raw[i], ans.ref.ptr[i]);
    }
    return ans;
  }

  @protected
  ffi.Pointer<wire_cst_list_subtitles> cst_encode_list_subtitles(
      List<Subtitles> raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    final ans = wire.cst_new_list_subtitles(raw.length);
    for (var i = 0; i < raw.length; ++i) {
      cst_api_fill_to_wire_subtitles(raw[i], ans.ref.ptr[i]);
    }
    return ans;
  }

  @protected
  ffi.Pointer<wire_cst_list_record_string_string>
      cst_encode_opt_Map_String_String(Map<String, String>? raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw == null ? ffi.nullptr : cst_encode_Map_String_String(raw);
  }

  @protected
  ffi.Pointer<wire_cst_list_prim_u_8_strict> cst_encode_opt_String(
      String? raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw == null ? ffi.nullptr : cst_encode_String(raw);
  }

  @protected
  ffi.Pointer<ffi.UintPtr>
      cst_encode_opt_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCancelToken(
          CancelToken? raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw == null
        ? ffi.nullptr
        : cst_encode_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCancelToken(
            raw);
  }

  @protected
  ffi.Pointer<ffi.Bool> cst_encode_opt_box_autoadd_bool(bool? raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw == null ? ffi.nullptr : cst_encode_box_autoadd_bool(raw);
  }

  @protected
  ffi.Pointer<wire_cst_entry> cst_encode_opt_box_autoadd_entry(Entry? raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw == null ? ffi.nullptr : cst_encode_box_autoadd_entry(raw);
  }

  @protected
  ffi.Pointer<ffi.Float> cst_encode_opt_box_autoadd_f_32(double? raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw == null ? ffi.nullptr : cst_encode_box_autoadd_f_32(raw);
  }

  @protected
  ffi.Pointer<ffi.Int64> cst_encode_opt_box_autoadd_i_64(PlatformInt64? raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw == null ? ffi.nullptr : cst_encode_box_autoadd_i_64(raw);
  }

  @protected
  ffi.Pointer<wire_cst_setting_ui> cst_encode_opt_box_autoadd_setting_ui(
      SettingUI? raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw == null ? ffi.nullptr : cst_encode_box_autoadd_setting_ui(raw);
  }

  @protected
  ffi.Pointer<wire_cst_list_String> cst_encode_opt_list_String(
      List<String>? raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw == null ? ffi.nullptr : cst_encode_list_String(raw);
  }

  @protected
  ffi.Pointer<wire_cst_list_media_type> cst_encode_opt_list_media_type(
      List<MediaType>? raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw == null ? ffi.nullptr : cst_encode_list_media_type(raw);
  }

  @protected
  int cst_encode_usize(BigInt raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw.toSigned(64).toInt();
  }

  @protected
  void cst_api_fill_to_wire_box_autoadd_data_source(
      DataSource apiObj, ffi.Pointer<wire_cst_data_source> wireObj) {
    cst_api_fill_to_wire_data_source(apiObj, wireObj.ref);
  }

  @protected
  void cst_api_fill_to_wire_box_autoadd_entry(
      Entry apiObj, ffi.Pointer<wire_cst_entry> wireObj) {
    cst_api_fill_to_wire_entry(apiObj, wireObj.ref);
  }

  @protected
  void cst_api_fill_to_wire_box_autoadd_link_source(
      LinkSource apiObj, ffi.Pointer<wire_cst_link_source> wireObj) {
    cst_api_fill_to_wire_link_source(apiObj, wireObj.ref);
  }

  @protected
  void cst_api_fill_to_wire_box_autoadd_permission(
      Permission apiObj, ffi.Pointer<wire_cst_permission> wireObj) {
    cst_api_fill_to_wire_permission(apiObj, wireObj.ref);
  }

  @protected
  void cst_api_fill_to_wire_box_autoadd_setting_ui(
      SettingUI apiObj, ffi.Pointer<wire_cst_setting_ui> wireObj) {
    cst_api_fill_to_wire_setting_ui(apiObj, wireObj.ref);
  }

  @protected
  void cst_api_fill_to_wire_box_autoadd_settingvalue(
      Settingvalue apiObj, ffi.Pointer<wire_cst_settingvalue> wireObj) {
    cst_api_fill_to_wire_settingvalue(apiObj, wireObj.ref);
  }

  @protected
  void cst_api_fill_to_wire_data_source(
      DataSource apiObj, wire_cst_data_source wireObj) {
    if (apiObj is DataSource_Paragraphlist) {
      var pre_paragraphs = cst_encode_list_String(apiObj.paragraphs);
      wireObj.tag = 0;
      wireObj.kind.Paragraphlist.paragraphs = pre_paragraphs;
      return;
    }
  }

  @protected
  void cst_api_fill_to_wire_entry(Entry apiObj, wire_cst_entry wireObj) {
    wireObj.id = cst_encode_String(apiObj.id);
    wireObj.url = cst_encode_String(apiObj.url);
    wireObj.title = cst_encode_String(apiObj.title);
    wireObj.media_type = cst_encode_media_type(apiObj.mediaType);
    wireObj.cover = cst_encode_opt_String(apiObj.cover);
    wireObj.cover_header = cst_encode_opt_Map_String_String(apiObj.coverHeader);
    wireObj.auther = cst_encode_opt_list_String(apiObj.auther);
    wireObj.rating = cst_encode_opt_box_autoadd_f_32(apiObj.rating);
    wireObj.views = cst_encode_opt_box_autoadd_f_32(apiObj.views);
    wireObj.length = cst_encode_opt_box_autoadd_i_64(apiObj.length);
  }

  @protected
  void cst_api_fill_to_wire_entry_detailed(
      EntryDetailed apiObj, wire_cst_entry_detailed wireObj) {
    wireObj.id = cst_encode_String(apiObj.id);
    wireObj.url = cst_encode_String(apiObj.url);
    wireObj.title = cst_encode_String(apiObj.title);
    wireObj.media_type = cst_encode_media_type(apiObj.mediaType);
    wireObj.status = cst_encode_release_status(apiObj.status);
    wireObj.cover = cst_encode_opt_String(apiObj.cover);
    wireObj.cover_header = cst_encode_opt_Map_String_String(apiObj.coverHeader);
    wireObj.episodes = cst_encode_list_episode_list(apiObj.episodes);
    wireObj.genres = cst_encode_opt_list_String(apiObj.genres);
    wireObj.alttitles = cst_encode_opt_list_String(apiObj.alttitles);
    wireObj.auther = cst_encode_opt_list_String(apiObj.auther);
    wireObj.rating = cst_encode_opt_box_autoadd_f_32(apiObj.rating);
    wireObj.views = cst_encode_opt_box_autoadd_f_32(apiObj.views);
    wireObj.length = cst_encode_opt_box_autoadd_i_64(apiObj.length);
  }

  @protected
  void cst_api_fill_to_wire_episode(Episode apiObj, wire_cst_episode wireObj) {
    wireObj.id = cst_encode_String(apiObj.id);
    wireObj.name = cst_encode_String(apiObj.name);
    wireObj.url = cst_encode_String(apiObj.url);
    wireObj.cover = cst_encode_opt_String(apiObj.cover);
    wireObj.cover_header = cst_encode_opt_Map_String_String(apiObj.coverHeader);
    wireObj.timestamp = cst_encode_opt_String(apiObj.timestamp);
  }

  @protected
  void cst_api_fill_to_wire_episode_list(
      EpisodeList apiObj, wire_cst_episode_list wireObj) {
    wireObj.title = cst_encode_String(apiObj.title);
    wireObj.episodes = cst_encode_list_episode(apiObj.episodes);
  }

  @protected
  void cst_api_fill_to_wire_extension_data(
      ExtensionData apiObj, wire_cst_extension_data wireObj) {
    wireObj.id = cst_encode_String(apiObj.id);
    wireObj.repo = cst_encode_opt_String(apiObj.repo);
    wireObj.name = cst_encode_String(apiObj.name);
    wireObj.media_type = cst_encode_opt_list_media_type(apiObj.mediaType);
    wireObj.giturl = cst_encode_opt_String(apiObj.giturl);
    wireObj.version = cst_encode_opt_String(apiObj.version);
    wireObj.desc = cst_encode_opt_String(apiObj.desc);
    wireObj.author = cst_encode_opt_String(apiObj.author);
    wireObj.license = cst_encode_opt_String(apiObj.license);
    wireObj.tags = cst_encode_opt_list_String(apiObj.tags);
    wireObj.nsfw = cst_encode_opt_box_autoadd_bool(apiObj.nsfw);
    wireObj.lang = cst_encode_list_String(apiObj.lang);
    wireObj.url = cst_encode_opt_String(apiObj.url);
    wireObj.icon = cst_encode_opt_String(apiObj.icon);
  }

  @protected
  void cst_api_fill_to_wire_image_list_audio(
      ImageListAudio apiObj, wire_cst_image_list_audio wireObj) {
    wireObj.link = cst_encode_String(apiObj.link);
    wireObj.from = cst_encode_i_64(apiObj.from);
    wireObj.to = cst_encode_i_64(apiObj.to);
  }

  @protected
  void cst_api_fill_to_wire_link_source(
      LinkSource apiObj, wire_cst_link_source wireObj) {
    if (apiObj is LinkSource_Epub) {
      var pre_link = cst_encode_String(apiObj.link);
      wireObj.tag = 0;
      wireObj.kind.Epub.link = pre_link;
      return;
    }
    if (apiObj is LinkSource_Pdf) {
      var pre_link = cst_encode_String(apiObj.link);
      wireObj.tag = 1;
      wireObj.kind.Pdf.link = pre_link;
      return;
    }
    if (apiObj is LinkSource_Imagelist) {
      var pre_links = cst_encode_list_String(apiObj.links);
      var pre_header = cst_encode_Map_String_String(apiObj.header);
      var pre_audio = cst_encode_list_image_list_audio(apiObj.audio);
      wireObj.tag = 2;
      wireObj.kind.Imagelist.links = pre_links;
      wireObj.kind.Imagelist.header = pre_header;
      wireObj.kind.Imagelist.audio = pre_audio;
      return;
    }
    if (apiObj is LinkSource_M3u8) {
      var pre_link = cst_encode_String(apiObj.link);
      var pre_sub = cst_encode_list_subtitles(apiObj.sub);
      wireObj.tag = 3;
      wireObj.kind.M3u8.link = pre_link;
      wireObj.kind.M3u8.sub = pre_sub;
      return;
    }
  }

  @protected
  void cst_api_fill_to_wire_permission(
      Permission apiObj, wire_cst_permission wireObj) {
    if (apiObj is Permission_StoragePermission) {
      var pre_path = cst_encode_String(apiObj.path);
      var pre_write = cst_encode_bool(apiObj.write);
      wireObj.tag = 0;
      wireObj.kind.StoragePermission.path = pre_path;
      wireObj.kind.StoragePermission.write = pre_write;
      return;
    }
  }

  @protected
  void cst_api_fill_to_wire_permission_request(
      PermissionRequest apiObj, wire_cst_permission_request wireObj) {
    cst_api_fill_to_wire_permission(apiObj.permission, wireObj.permission);
    wireObj.msg = cst_encode_opt_String(apiObj.msg);
  }

  @protected
  void cst_api_fill_to_wire_record_string_string(
      (String, String) apiObj, wire_cst_record_string_string wireObj) {
    wireObj.field0 = cst_encode_String(apiObj.$1);
    wireObj.field1 = cst_encode_String(apiObj.$2);
  }

  @protected
  void cst_api_fill_to_wire_setting(Setting apiObj, wire_cst_setting wireObj) {
    cst_api_fill_to_wire_settingvalue(apiObj.val, wireObj.val);
    wireObj.settingtype = cst_encode_settingtype(apiObj.settingtype);
    wireObj.ui = cst_encode_opt_box_autoadd_setting_ui(apiObj.ui);
  }

  @protected
  void cst_api_fill_to_wire_setting_ui(
      SettingUI apiObj, wire_cst_setting_ui wireObj) {
    if (apiObj is SettingUI_PathSelection) {
      var pre_label = cst_encode_String(apiObj.label);
      var pre_pickfolder = cst_encode_bool(apiObj.pickfolder);
      wireObj.tag = 0;
      wireObj.kind.PathSelection.label = pre_label;
      wireObj.kind.PathSelection.pickfolder = pre_pickfolder;
      return;
    }
    if (apiObj is SettingUI_Slider) {
      var pre_label = cst_encode_String(apiObj.label);
      var pre_min = cst_encode_f_64(apiObj.min);
      var pre_max = cst_encode_f_64(apiObj.max);
      var pre_step = cst_encode_f_64(apiObj.step);
      wireObj.tag = 1;
      wireObj.kind.Slider.label = pre_label;
      wireObj.kind.Slider.min = pre_min;
      wireObj.kind.Slider.max = pre_max;
      wireObj.kind.Slider.step = pre_step;
      return;
    }
    if (apiObj is SettingUI_Checkbox) {
      var pre_label = cst_encode_String(apiObj.label);
      wireObj.tag = 2;
      wireObj.kind.Checkbox.label = pre_label;
      return;
    }
    if (apiObj is SettingUI_Textbox) {
      var pre_label = cst_encode_String(apiObj.label);
      wireObj.tag = 3;
      wireObj.kind.Textbox.label = pre_label;
      return;
    }
    if (apiObj is SettingUI_Dropdown) {
      var pre_label = cst_encode_String(apiObj.label);
      var pre_options = cst_encode_list_record_string_string(apiObj.options);
      wireObj.tag = 4;
      wireObj.kind.Dropdown.label = pre_label;
      wireObj.kind.Dropdown.options = pre_options;
      return;
    }
  }

  @protected
  void cst_api_fill_to_wire_settingvalue(
      Settingvalue apiObj, wire_cst_settingvalue wireObj) {
    if (apiObj is Settingvalue_String) {
      var pre_val = cst_encode_String(apiObj.val);
      var pre_default_val = cst_encode_String(apiObj.defaultVal);
      wireObj.tag = 0;
      wireObj.kind.String.val = pre_val;
      wireObj.kind.String.default_val = pre_default_val;
      return;
    }
    if (apiObj is Settingvalue_Number) {
      var pre_val = cst_encode_f_64(apiObj.val);
      var pre_default_val = cst_encode_f_64(apiObj.defaultVal);
      wireObj.tag = 1;
      wireObj.kind.Number.val = pre_val;
      wireObj.kind.Number.default_val = pre_default_val;
      return;
    }
    if (apiObj is Settingvalue_Boolean) {
      var pre_val = cst_encode_bool(apiObj.val);
      var pre_default_val = cst_encode_bool(apiObj.defaultVal);
      wireObj.tag = 2;
      wireObj.kind.Boolean.val = pre_val;
      wireObj.kind.Boolean.default_val = pre_default_val;
      return;
    }
  }

  @protected
  void cst_api_fill_to_wire_source(Source apiObj, wire_cst_source wireObj) {
    if (apiObj is Source_Data) {
      var pre_sourcedata =
          cst_encode_box_autoadd_data_source(apiObj.sourcedata);
      wireObj.tag = 0;
      wireObj.kind.Data.sourcedata = pre_sourcedata;
      return;
    }
    if (apiObj is Source_Directlink) {
      var pre_sourcedata =
          cst_encode_box_autoadd_link_source(apiObj.sourcedata);
      wireObj.tag = 1;
      wireObj.kind.Directlink.sourcedata = pre_sourcedata;
      return;
    }
  }

  @protected
  void cst_api_fill_to_wire_subtitles(
      Subtitles apiObj, wire_cst_subtitles wireObj) {
    wireObj.title = cst_encode_String(apiObj.title);
    wireObj.url = cst_encode_String(apiObj.url);
  }

  @protected
  int cst_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCancelToken(
      CancelToken raw);

  @protected
  int cst_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerExtensionManagerProxy(
      ExtensionManagerProxy raw);

  @protected
  int cst_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerExtensionProxy(
      ExtensionProxy raw);

  @protected
  int cst_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerQueueStore(
      QueueStore raw);

  @protected
  int cst_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerExtensionManagerProxy(
      ExtensionManagerProxy raw);

  @protected
  int cst_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerExtensionManagerProxy(
      ExtensionManagerProxy raw);

  @protected
  int cst_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerExtensionProxy(
      ExtensionProxy raw);

  @protected
  int cst_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCancelToken(
      CancelToken raw);

  @protected
  int cst_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerExtensionManagerProxy(
      ExtensionManagerProxy raw);

  @protected
  int cst_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerExtensionProxy(
      ExtensionProxy raw);

  @protected
  int cst_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerQueueStore(
      QueueStore raw);

  @protected
  bool cst_encode_bool(bool raw);

  @protected
  double cst_encode_f_32(double raw);

  @protected
  double cst_encode_f_64(double raw);

  @protected
  int cst_encode_i_32(int raw);

  @protected
  int cst_encode_media_type(MediaType raw);

  @protected
  int cst_encode_release_status(ReleaseStatus raw);

  @protected
  int cst_encode_settingtype(Settingtype raw);

  @protected
  int cst_encode_sort(Sort raw);

  @protected
  int cst_encode_u_8(int raw);

  @protected
  void cst_encode_unit(void raw);

  @protected
  void sse_encode_AnyhowException(
      AnyhowException self, SseSerializer serializer);

  @protected
  void
      sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCancelToken(
          CancelToken self, SseSerializer serializer);

  @protected
  void
      sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerExtensionManagerProxy(
          ExtensionManagerProxy self, SseSerializer serializer);

  @protected
  void
      sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerExtensionProxy(
          ExtensionProxy self, SseSerializer serializer);

  @protected
  void
      sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerQueueStore(
          QueueStore self, SseSerializer serializer);

  @protected
  void
      sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerExtensionManagerProxy(
          ExtensionManagerProxy self, SseSerializer serializer);

  @protected
  void
      sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerExtensionManagerProxy(
          ExtensionManagerProxy self, SseSerializer serializer);

  @protected
  void
      sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerExtensionProxy(
          ExtensionProxy self, SseSerializer serializer);

  @protected
  void sse_encode_Map_String_String(
      Map<String, String> self, SseSerializer serializer);

  @protected
  void
      sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCancelToken(
          CancelToken self, SseSerializer serializer);

  @protected
  void
      sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerExtensionManagerProxy(
          ExtensionManagerProxy self, SseSerializer serializer);

  @protected
  void
      sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerExtensionProxy(
          ExtensionProxy self, SseSerializer serializer);

  @protected
  void
      sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerQueueStore(
          QueueStore self, SseSerializer serializer);

  @protected
  void sse_encode_StreamSink_permission_request_Dco(
      RustStreamSink<PermissionRequest> self, SseSerializer serializer);

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void
      sse_encode_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCancelToken(
          CancelToken self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_data_source(
      DataSource self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_entry(Entry self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_f_32(double self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_i_64(
      PlatformInt64 self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_link_source(
      LinkSource self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_permission(
      Permission self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_setting_ui(
      SettingUI self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_settingvalue(
      Settingvalue self, SseSerializer serializer);

  @protected
  void sse_encode_data_source(DataSource self, SseSerializer serializer);

  @protected
  void sse_encode_entry(Entry self, SseSerializer serializer);

  @protected
  void sse_encode_entry_detailed(EntryDetailed self, SseSerializer serializer);

  @protected
  void sse_encode_episode(Episode self, SseSerializer serializer);

  @protected
  void sse_encode_episode_list(EpisodeList self, SseSerializer serializer);

  @protected
  void sse_encode_extension_data(ExtensionData self, SseSerializer serializer);

  @protected
  void sse_encode_f_32(double self, SseSerializer serializer);

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer);

  @protected
  void sse_encode_image_list_audio(
      ImageListAudio self, SseSerializer serializer);

  @protected
  void sse_encode_link_source(LinkSource self, SseSerializer serializer);

  @protected
  void
      sse_encode_list_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerExtensionProxy(
          List<ExtensionProxy> self, SseSerializer serializer);

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_entry(List<Entry> self, SseSerializer serializer);

  @protected
  void sse_encode_list_episode(List<Episode> self, SseSerializer serializer);

  @protected
  void sse_encode_list_episode_list(
      List<EpisodeList> self, SseSerializer serializer);

  @protected
  void sse_encode_list_image_list_audio(
      List<ImageListAudio> self, SseSerializer serializer);

  @protected
  void sse_encode_list_media_type(
      List<MediaType> self, SseSerializer serializer);

  @protected
  void sse_encode_list_permission(
      List<Permission> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_strict(
      Uint8List self, SseSerializer serializer);

  @protected
  void sse_encode_list_record_string_string(
      List<(String, String)> self, SseSerializer serializer);

  @protected
  void sse_encode_list_subtitles(
      List<Subtitles> self, SseSerializer serializer);

  @protected
  void sse_encode_media_type(MediaType self, SseSerializer serializer);

  @protected
  void sse_encode_opt_Map_String_String(
      Map<String, String>? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void
      sse_encode_opt_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCancelToken(
          CancelToken? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_bool(bool? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_entry(Entry? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_f_32(double? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_i_64(
      PlatformInt64? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_setting_ui(
      SettingUI? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_list_String(List<String>? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_list_media_type(
      List<MediaType>? self, SseSerializer serializer);

  @protected
  void sse_encode_permission(Permission self, SseSerializer serializer);

  @protected
  void sse_encode_permission_request(
      PermissionRequest self, SseSerializer serializer);

  @protected
  void sse_encode_record_string_string(
      (String, String) self, SseSerializer serializer);

  @protected
  void sse_encode_release_status(ReleaseStatus self, SseSerializer serializer);

  @protected
  void sse_encode_setting(Setting self, SseSerializer serializer);

  @protected
  void sse_encode_setting_ui(SettingUI self, SseSerializer serializer);

  @protected
  void sse_encode_settingtype(Settingtype self, SseSerializer serializer);

  @protected
  void sse_encode_settingvalue(Settingvalue self, SseSerializer serializer);

  @protected
  void sse_encode_sort(Sort self, SseSerializer serializer);

  @protected
  void sse_encode_source(Source self, SseSerializer serializer);

  @protected
  void sse_encode_subtitles(Subtitles self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer);
}

// Section: wire_class

// ignore_for_file: camel_case_types, non_constant_identifier_names, avoid_positional_boolean_parameters, annotate_overrides, constant_identifier_names
// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint

/// generated by flutter_rust_bridge
class RustLibWire implements BaseWire {
  factory RustLibWire.fromExternalLibrary(ExternalLibrary lib) =>
      RustLibWire(lib.ffiDynamicLibrary);

  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
      _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  RustLibWire(ffi.DynamicLibrary dynamicLibrary)
      : _lookup = dynamicLibrary.lookup;

  /// The symbols are looked up with [lookup].
  RustLibWire.fromLookup(
      ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
          lookup)
      : _lookup = lookup;

  void store_dart_post_cobject(
    DartPostCObjectFnType ptr,
  ) {
    return _store_dart_post_cobject(
      ptr,
    );
  }

  late final _store_dart_post_cobjectPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(DartPostCObjectFnType)>>(
          'store_dart_post_cobject');
  late final _store_dart_post_cobject = _store_dart_post_cobjectPtr
      .asFunction<void Function(DartPostCObjectFnType)>();

  WireSyncRust2DartDco wire__crate__api__simple__CancelToken_new() {
    return _wire__crate__api__simple__CancelToken_new();
  }

  late final _wire__crate__api__simple__CancelToken_newPtr =
      _lookup<ffi.NativeFunction<WireSyncRust2DartDco Function()>>(
          'frbgen_rdion_runtime_wire__crate__api__simple__CancelToken_new');
  late final _wire__crate__api__simple__CancelToken_new =
      _wire__crate__api__simple__CancelToken_newPtr
          .asFunction<WireSyncRust2DartDco Function()>();

  void wire__crate__api__simple__ExtensionManagerProxy_add_from_file(
    int port_,
    int that,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> path,
  ) {
    return _wire__crate__api__simple__ExtensionManagerProxy_add_from_file(
      port_,
      that,
      path,
    );
  }

  late final _wire__crate__api__simple__ExtensionManagerProxy_add_from_filePtr =
      _lookup<
              ffi.NativeFunction<
                  ffi.Void Function(ffi.Int64, ffi.UintPtr,
                      ffi.Pointer<wire_cst_list_prim_u_8_strict>)>>(
          'frbgen_rdion_runtime_wire__crate__api__simple__ExtensionManagerProxy_add_from_file');
  late final _wire__crate__api__simple__ExtensionManagerProxy_add_from_file =
      _wire__crate__api__simple__ExtensionManagerProxy_add_from_filePtr
          .asFunction<
              void Function(
                  int, int, ffi.Pointer<wire_cst_list_prim_u_8_strict>)>();

  void wire__crate__api__simple__ExtensionManagerProxy_iter(
    int port_,
    int that,
  ) {
    return _wire__crate__api__simple__ExtensionManagerProxy_iter(
      port_,
      that,
    );
  }

  late final _wire__crate__api__simple__ExtensionManagerProxy_iterPtr = _lookup<
          ffi.NativeFunction<ffi.Void Function(ffi.Int64, ffi.UintPtr)>>(
      'frbgen_rdion_runtime_wire__crate__api__simple__ExtensionManagerProxy_iter');
  late final _wire__crate__api__simple__ExtensionManagerProxy_iter =
      _wire__crate__api__simple__ExtensionManagerProxy_iterPtr
          .asFunction<void Function(int, int)>();

  WireSyncRust2DartDco wire__crate__api__simple__ExtensionManagerProxy_new() {
    return _wire__crate__api__simple__ExtensionManagerProxy_new();
  }

  late final _wire__crate__api__simple__ExtensionManagerProxy_newPtr = _lookup<
          ffi.NativeFunction<WireSyncRust2DartDco Function()>>(
      'frbgen_rdion_runtime_wire__crate__api__simple__ExtensionManagerProxy_new');
  late final _wire__crate__api__simple__ExtensionManagerProxy_new =
      _wire__crate__api__simple__ExtensionManagerProxy_newPtr
          .asFunction<WireSyncRust2DartDco Function()>();

  void wire__crate__api__simple__ExtensionManagerProxy_remove(
    int port_,
    int that,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> id,
  ) {
    return _wire__crate__api__simple__ExtensionManagerProxy_remove(
      port_,
      that,
      id,
    );
  }

  late final _wire__crate__api__simple__ExtensionManagerProxy_removePtr = _lookup<
          ffi.NativeFunction<
              ffi.Void Function(ffi.Int64, ffi.UintPtr,
                  ffi.Pointer<wire_cst_list_prim_u_8_strict>)>>(
      'frbgen_rdion_runtime_wire__crate__api__simple__ExtensionManagerProxy_remove');
  late final _wire__crate__api__simple__ExtensionManagerProxy_remove =
      _wire__crate__api__simple__ExtensionManagerProxy_removePtr.asFunction<
          void Function(
              int, int, ffi.Pointer<wire_cst_list_prim_u_8_strict>)>();

  void wire__crate__api__simple__ExtensionProxy_browse(
    int port_,
    int that,
    int page,
    int sort,
    ffi.Pointer<ffi.UintPtr> token,
  ) {
    return _wire__crate__api__simple__ExtensionProxy_browse(
      port_,
      that,
      page,
      sort,
      token,
    );
  }

  late final _wire__crate__api__simple__ExtensionProxy_browsePtr = _lookup<
          ffi.NativeFunction<
              ffi.Void Function(ffi.Int64, ffi.UintPtr, ffi.Int64, ffi.Int32,
                  ffi.Pointer<ffi.UintPtr>)>>(
      'frbgen_rdion_runtime_wire__crate__api__simple__ExtensionProxy_browse');
  late final _wire__crate__api__simple__ExtensionProxy_browse =
      _wire__crate__api__simple__ExtensionProxy_browsePtr.asFunction<
          void Function(int, int, int, int, ffi.Pointer<ffi.UintPtr>)>();

  void wire__crate__api__simple__ExtensionProxy_data(
    int port_,
    int that,
  ) {
    return _wire__crate__api__simple__ExtensionProxy_data(
      port_,
      that,
    );
  }

  late final _wire__crate__api__simple__ExtensionProxy_dataPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Int64, ffi.UintPtr)>>(
          'frbgen_rdion_runtime_wire__crate__api__simple__ExtensionProxy_data');
  late final _wire__crate__api__simple__ExtensionProxy_data =
      _wire__crate__api__simple__ExtensionProxy_dataPtr
          .asFunction<void Function(int, int)>();

  void wire__crate__api__simple__ExtensionProxy_detail(
    int port_,
    int that,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> entryid,
    ffi.Pointer<ffi.UintPtr> token,
  ) {
    return _wire__crate__api__simple__ExtensionProxy_detail(
      port_,
      that,
      entryid,
      token,
    );
  }

  late final _wire__crate__api__simple__ExtensionProxy_detailPtr = _lookup<
          ffi.NativeFunction<
              ffi.Void Function(
                  ffi.Int64,
                  ffi.UintPtr,
                  ffi.Pointer<wire_cst_list_prim_u_8_strict>,
                  ffi.Pointer<ffi.UintPtr>)>>(
      'frbgen_rdion_runtime_wire__crate__api__simple__ExtensionProxy_detail');
  late final _wire__crate__api__simple__ExtensionProxy_detail =
      _wire__crate__api__simple__ExtensionProxy_detailPtr.asFunction<
          void Function(int, int, ffi.Pointer<wire_cst_list_prim_u_8_strict>,
              ffi.Pointer<ffi.UintPtr>)>();

  void wire__crate__api__simple__ExtensionProxy_disable(
    int port_,
    int that,
  ) {
    return _wire__crate__api__simple__ExtensionProxy_disable(
      port_,
      that,
    );
  }

  late final _wire__crate__api__simple__ExtensionProxy_disablePtr = _lookup<
          ffi.NativeFunction<ffi.Void Function(ffi.Int64, ffi.UintPtr)>>(
      'frbgen_rdion_runtime_wire__crate__api__simple__ExtensionProxy_disable');
  late final _wire__crate__api__simple__ExtensionProxy_disable =
      _wire__crate__api__simple__ExtensionProxy_disablePtr
          .asFunction<void Function(int, int)>();

  void wire__crate__api__simple__ExtensionProxy_enable(
    int port_,
    int that,
  ) {
    return _wire__crate__api__simple__ExtensionProxy_enable(
      port_,
      that,
    );
  }

  late final _wire__crate__api__simple__ExtensionProxy_enablePtr = _lookup<
          ffi.NativeFunction<ffi.Void Function(ffi.Int64, ffi.UintPtr)>>(
      'frbgen_rdion_runtime_wire__crate__api__simple__ExtensionProxy_enable');
  late final _wire__crate__api__simple__ExtensionProxy_enable =
      _wire__crate__api__simple__ExtensionProxy_enablePtr
          .asFunction<void Function(int, int)>();

  void wire__crate__api__simple__ExtensionProxy_fromurl(
    int port_,
    int that,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> url,
    ffi.Pointer<ffi.UintPtr> token,
  ) {
    return _wire__crate__api__simple__ExtensionProxy_fromurl(
      port_,
      that,
      url,
      token,
    );
  }

  late final _wire__crate__api__simple__ExtensionProxy_fromurlPtr = _lookup<
          ffi.NativeFunction<
              ffi.Void Function(
                  ffi.Int64,
                  ffi.UintPtr,
                  ffi.Pointer<wire_cst_list_prim_u_8_strict>,
                  ffi.Pointer<ffi.UintPtr>)>>(
      'frbgen_rdion_runtime_wire__crate__api__simple__ExtensionProxy_fromurl');
  late final _wire__crate__api__simple__ExtensionProxy_fromurl =
      _wire__crate__api__simple__ExtensionProxy_fromurlPtr.asFunction<
          void Function(int, int, ffi.Pointer<wire_cst_list_prim_u_8_strict>,
              ffi.Pointer<ffi.UintPtr>)>();

  void wire__crate__api__simple__ExtensionProxy_get_setting(
    int port_,
    int that,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> name,
  ) {
    return _wire__crate__api__simple__ExtensionProxy_get_setting(
      port_,
      that,
      name,
    );
  }

  late final _wire__crate__api__simple__ExtensionProxy_get_settingPtr = _lookup<
          ffi.NativeFunction<
              ffi.Void Function(ffi.Int64, ffi.UintPtr,
                  ffi.Pointer<wire_cst_list_prim_u_8_strict>)>>(
      'frbgen_rdion_runtime_wire__crate__api__simple__ExtensionProxy_get_setting');
  late final _wire__crate__api__simple__ExtensionProxy_get_setting =
      _wire__crate__api__simple__ExtensionProxy_get_settingPtr.asFunction<
          void Function(
              int, int, ffi.Pointer<wire_cst_list_prim_u_8_strict>)>();

  void wire__crate__api__simple__ExtensionProxy_is_enabled(
    int port_,
    int that,
  ) {
    return _wire__crate__api__simple__ExtensionProxy_is_enabled(
      port_,
      that,
    );
  }

  late final _wire__crate__api__simple__ExtensionProxy_is_enabledPtr = _lookup<
          ffi.NativeFunction<ffi.Void Function(ffi.Int64, ffi.UintPtr)>>(
      'frbgen_rdion_runtime_wire__crate__api__simple__ExtensionProxy_is_enabled');
  late final _wire__crate__api__simple__ExtensionProxy_is_enabled =
      _wire__crate__api__simple__ExtensionProxy_is_enabledPtr
          .asFunction<void Function(int, int)>();

  void wire__crate__api__simple__ExtensionProxy_new(
    int port_,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> filepath,
  ) {
    return _wire__crate__api__simple__ExtensionProxy_new(
      port_,
      filepath,
    );
  }

  late final _wire__crate__api__simple__ExtensionProxy_newPtr = _lookup<
          ffi.NativeFunction<
              ffi.Void Function(
                  ffi.Int64, ffi.Pointer<wire_cst_list_prim_u_8_strict>)>>(
      'frbgen_rdion_runtime_wire__crate__api__simple__ExtensionProxy_new');
  late final _wire__crate__api__simple__ExtensionProxy_new =
      _wire__crate__api__simple__ExtensionProxy_newPtr.asFunction<
          void Function(int, ffi.Pointer<wire_cst_list_prim_u_8_strict>)>();

  void wire__crate__api__simple__ExtensionProxy_permissions_iter(
    int port_,
    int that,
  ) {
    return _wire__crate__api__simple__ExtensionProxy_permissions_iter(
      port_,
      that,
    );
  }

  late final _wire__crate__api__simple__ExtensionProxy_permissions_iterPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Int64, ffi.UintPtr)>>(
          'frbgen_rdion_runtime_wire__crate__api__simple__ExtensionProxy_permissions_iter');
  late final _wire__crate__api__simple__ExtensionProxy_permissions_iter =
      _wire__crate__api__simple__ExtensionProxy_permissions_iterPtr
          .asFunction<void Function(int, int)>();

  void wire__crate__api__simple__ExtensionProxy_remove_permissions(
    int port_,
    int that,
    ffi.Pointer<wire_cst_permission> permission,
  ) {
    return _wire__crate__api__simple__ExtensionProxy_remove_permissions(
      port_,
      that,
      permission,
    );
  }

  late final _wire__crate__api__simple__ExtensionProxy_remove_permissionsPtr =
      _lookup<
              ffi.NativeFunction<
                  ffi.Void Function(ffi.Int64, ffi.UintPtr,
                      ffi.Pointer<wire_cst_permission>)>>(
          'frbgen_rdion_runtime_wire__crate__api__simple__ExtensionProxy_remove_permissions');
  late final _wire__crate__api__simple__ExtensionProxy_remove_permissions =
      _wire__crate__api__simple__ExtensionProxy_remove_permissionsPtr
          .asFunction<
              void Function(int, int, ffi.Pointer<wire_cst_permission>)>();

  void wire__crate__api__simple__ExtensionProxy_search(
    int port_,
    int that,
    int page,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> filter,
    ffi.Pointer<ffi.UintPtr> token,
  ) {
    return _wire__crate__api__simple__ExtensionProxy_search(
      port_,
      that,
      page,
      filter,
      token,
    );
  }

  late final _wire__crate__api__simple__ExtensionProxy_searchPtr = _lookup<
          ffi.NativeFunction<
              ffi.Void Function(
                  ffi.Int64,
                  ffi.UintPtr,
                  ffi.Int64,
                  ffi.Pointer<wire_cst_list_prim_u_8_strict>,
                  ffi.Pointer<ffi.UintPtr>)>>(
      'frbgen_rdion_runtime_wire__crate__api__simple__ExtensionProxy_search');
  late final _wire__crate__api__simple__ExtensionProxy_search =
      _wire__crate__api__simple__ExtensionProxy_searchPtr.asFunction<
          void Function(
              int,
              int,
              int,
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
              ffi.Pointer<ffi.UintPtr>)>();

  void wire__crate__api__simple__ExtensionProxy_set_setting(
    int port_,
    int that,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> name,
    ffi.Pointer<wire_cst_settingvalue> setting,
  ) {
    return _wire__crate__api__simple__ExtensionProxy_set_setting(
      port_,
      that,
      name,
      setting,
    );
  }

  late final _wire__crate__api__simple__ExtensionProxy_set_settingPtr = _lookup<
          ffi.NativeFunction<
              ffi.Void Function(
                  ffi.Int64,
                  ffi.UintPtr,
                  ffi.Pointer<wire_cst_list_prim_u_8_strict>,
                  ffi.Pointer<wire_cst_settingvalue>)>>(
      'frbgen_rdion_runtime_wire__crate__api__simple__ExtensionProxy_set_setting');
  late final _wire__crate__api__simple__ExtensionProxy_set_setting =
      _wire__crate__api__simple__ExtensionProxy_set_settingPtr.asFunction<
          void Function(int, int, ffi.Pointer<wire_cst_list_prim_u_8_strict>,
              ffi.Pointer<wire_cst_settingvalue>)>();

  void wire__crate__api__simple__ExtensionProxy_setting_ids_iter(
    int port_,
    int that,
  ) {
    return _wire__crate__api__simple__ExtensionProxy_setting_ids_iter(
      port_,
      that,
    );
  }

  late final _wire__crate__api__simple__ExtensionProxy_setting_ids_iterPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Int64, ffi.UintPtr)>>(
          'frbgen_rdion_runtime_wire__crate__api__simple__ExtensionProxy_setting_ids_iter');
  late final _wire__crate__api__simple__ExtensionProxy_setting_ids_iter =
      _wire__crate__api__simple__ExtensionProxy_setting_ids_iterPtr
          .asFunction<void Function(int, int)>();

  void wire__crate__api__simple__ExtensionProxy_source(
    int port_,
    int that,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> epid,
    ffi.Pointer<ffi.UintPtr> token,
  ) {
    return _wire__crate__api__simple__ExtensionProxy_source(
      port_,
      that,
      epid,
      token,
    );
  }

  late final _wire__crate__api__simple__ExtensionProxy_sourcePtr = _lookup<
          ffi.NativeFunction<
              ffi.Void Function(
                  ffi.Int64,
                  ffi.UintPtr,
                  ffi.Pointer<wire_cst_list_prim_u_8_strict>,
                  ffi.Pointer<ffi.UintPtr>)>>(
      'frbgen_rdion_runtime_wire__crate__api__simple__ExtensionProxy_source');
  late final _wire__crate__api__simple__ExtensionProxy_source =
      _wire__crate__api__simple__ExtensionProxy_sourcePtr.asFunction<
          void Function(int, int, ffi.Pointer<wire_cst_list_prim_u_8_strict>,
              ffi.Pointer<ffi.UintPtr>)>();

  void wire__crate__api__simple__QueueStore_default(
    int port_,
  ) {
    return _wire__crate__api__simple__QueueStore_default(
      port_,
    );
  }

  late final _wire__crate__api__simple__QueueStore_defaultPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Int64)>>(
          'frbgen_rdion_runtime_wire__crate__api__simple__QueueStore_default');
  late final _wire__crate__api__simple__QueueStore_default =
      _wire__crate__api__simple__QueueStore_defaultPtr
          .asFunction<void Function(int)>();

  void wire__crate__api__simple__init_app(
    int port_,
  ) {
    return _wire__crate__api__simple__init_app(
      port_,
    );
  }

  late final _wire__crate__api__simple__init_appPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Int64)>>(
          'frbgen_rdion_runtime_wire__crate__api__simple__init_app');
  late final _wire__crate__api__simple__init_app =
      _wire__crate__api__simple__init_appPtr.asFunction<void Function(int)>();

  void wire__crate__api__simple__internal_send_permission_request_answer(
    int port_,
    bool answer,
  ) {
    return _wire__crate__api__simple__internal_send_permission_request_answer(
      port_,
      answer,
    );
  }

  late final _wire__crate__api__simple__internal_send_permission_request_answerPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Int64, ffi.Bool)>>(
          'frbgen_rdion_runtime_wire__crate__api__simple__internal_send_permission_request_answer');
  late final _wire__crate__api__simple__internal_send_permission_request_answer =
      _wire__crate__api__simple__internal_send_permission_request_answerPtr
          .asFunction<void Function(int, bool)>();

  void wire__crate__api__simple__internal_set_permission_request_listener(
    int port_,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> request,
  ) {
    return _wire__crate__api__simple__internal_set_permission_request_listener(
      port_,
      request,
    );
  }

  late final _wire__crate__api__simple__internal_set_permission_request_listenerPtr =
      _lookup<
              ffi.NativeFunction<
                  ffi.Void Function(
                      ffi.Int64, ffi.Pointer<wire_cst_list_prim_u_8_strict>)>>(
          'frbgen_rdion_runtime_wire__crate__api__simple__internal_set_permission_request_listener');
  late final _wire__crate__api__simple__internal_set_permission_request_listener =
      _wire__crate__api__simple__internal_set_permission_request_listenerPtr
          .asFunction<
              void Function(int, ffi.Pointer<wire_cst_list_prim_u_8_strict>)>();

  void
      rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCancelToken(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCancelToken(
      ptr,
    );
  }

  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCancelTokenPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
          'frbgen_rdion_runtime_rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCancelToken');
  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCancelToken =
      _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCancelTokenPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
      rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCancelToken(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCancelToken(
      ptr,
    );
  }

  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCancelTokenPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
          'frbgen_rdion_runtime_rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCancelToken');
  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCancelToken =
      _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCancelTokenPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
      rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerExtensionManagerProxy(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerExtensionManagerProxy(
      ptr,
    );
  }

  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerExtensionManagerProxyPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
          'frbgen_rdion_runtime_rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerExtensionManagerProxy');
  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerExtensionManagerProxy =
      _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerExtensionManagerProxyPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
      rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerExtensionManagerProxy(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerExtensionManagerProxy(
      ptr,
    );
  }

  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerExtensionManagerProxyPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
          'frbgen_rdion_runtime_rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerExtensionManagerProxy');
  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerExtensionManagerProxy =
      _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerExtensionManagerProxyPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
      rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerExtensionProxy(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerExtensionProxy(
      ptr,
    );
  }

  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerExtensionProxyPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
          'frbgen_rdion_runtime_rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerExtensionProxy');
  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerExtensionProxy =
      _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerExtensionProxyPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
      rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerExtensionProxy(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerExtensionProxy(
      ptr,
    );
  }

  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerExtensionProxyPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
          'frbgen_rdion_runtime_rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerExtensionProxy');
  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerExtensionProxy =
      _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerExtensionProxyPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
      rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerQueueStore(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerQueueStore(
      ptr,
    );
  }

  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerQueueStorePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
          'frbgen_rdion_runtime_rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerQueueStore');
  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerQueueStore =
      _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerQueueStorePtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
      rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerQueueStore(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerQueueStore(
      ptr,
    );
  }

  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerQueueStorePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
          'frbgen_rdion_runtime_rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerQueueStore');
  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerQueueStore =
      _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerQueueStorePtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  ffi.Pointer<ffi.UintPtr>
      cst_new_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCancelToken(
    int value,
  ) {
    return _cst_new_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCancelToken(
      value,
    );
  }

  late final _cst_new_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCancelTokenPtr =
      _lookup<
              ffi
              .NativeFunction<ffi.Pointer<ffi.UintPtr> Function(ffi.UintPtr)>>(
          'frbgen_rdion_runtime_cst_new_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCancelToken');
  late final _cst_new_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCancelToken =
      _cst_new_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCancelTokenPtr
          .asFunction<ffi.Pointer<ffi.UintPtr> Function(int)>();

  ffi.Pointer<ffi.Bool> cst_new_box_autoadd_bool(
    bool value,
  ) {
    return _cst_new_box_autoadd_bool(
      value,
    );
  }

  late final _cst_new_box_autoadd_boolPtr =
      _lookup<ffi.NativeFunction<ffi.Pointer<ffi.Bool> Function(ffi.Bool)>>(
          'frbgen_rdion_runtime_cst_new_box_autoadd_bool');
  late final _cst_new_box_autoadd_bool = _cst_new_box_autoadd_boolPtr
      .asFunction<ffi.Pointer<ffi.Bool> Function(bool)>();

  ffi.Pointer<wire_cst_data_source> cst_new_box_autoadd_data_source() {
    return _cst_new_box_autoadd_data_source();
  }

  late final _cst_new_box_autoadd_data_sourcePtr =
      _lookup<ffi.NativeFunction<ffi.Pointer<wire_cst_data_source> Function()>>(
          'frbgen_rdion_runtime_cst_new_box_autoadd_data_source');
  late final _cst_new_box_autoadd_data_source =
      _cst_new_box_autoadd_data_sourcePtr
          .asFunction<ffi.Pointer<wire_cst_data_source> Function()>();

  ffi.Pointer<wire_cst_entry> cst_new_box_autoadd_entry() {
    return _cst_new_box_autoadd_entry();
  }

  late final _cst_new_box_autoadd_entryPtr =
      _lookup<ffi.NativeFunction<ffi.Pointer<wire_cst_entry> Function()>>(
          'frbgen_rdion_runtime_cst_new_box_autoadd_entry');
  late final _cst_new_box_autoadd_entry = _cst_new_box_autoadd_entryPtr
      .asFunction<ffi.Pointer<wire_cst_entry> Function()>();

  ffi.Pointer<ffi.Float> cst_new_box_autoadd_f_32(
    double value,
  ) {
    return _cst_new_box_autoadd_f_32(
      value,
    );
  }

  late final _cst_new_box_autoadd_f_32Ptr =
      _lookup<ffi.NativeFunction<ffi.Pointer<ffi.Float> Function(ffi.Float)>>(
          'frbgen_rdion_runtime_cst_new_box_autoadd_f_32');
  late final _cst_new_box_autoadd_f_32 = _cst_new_box_autoadd_f_32Ptr
      .asFunction<ffi.Pointer<ffi.Float> Function(double)>();

  ffi.Pointer<ffi.Int64> cst_new_box_autoadd_i_64(
    int value,
  ) {
    return _cst_new_box_autoadd_i_64(
      value,
    );
  }

  late final _cst_new_box_autoadd_i_64Ptr =
      _lookup<ffi.NativeFunction<ffi.Pointer<ffi.Int64> Function(ffi.Int64)>>(
          'frbgen_rdion_runtime_cst_new_box_autoadd_i_64');
  late final _cst_new_box_autoadd_i_64 = _cst_new_box_autoadd_i_64Ptr
      .asFunction<ffi.Pointer<ffi.Int64> Function(int)>();

  ffi.Pointer<wire_cst_link_source> cst_new_box_autoadd_link_source() {
    return _cst_new_box_autoadd_link_source();
  }

  late final _cst_new_box_autoadd_link_sourcePtr =
      _lookup<ffi.NativeFunction<ffi.Pointer<wire_cst_link_source> Function()>>(
          'frbgen_rdion_runtime_cst_new_box_autoadd_link_source');
  late final _cst_new_box_autoadd_link_source =
      _cst_new_box_autoadd_link_sourcePtr
          .asFunction<ffi.Pointer<wire_cst_link_source> Function()>();

  ffi.Pointer<wire_cst_permission> cst_new_box_autoadd_permission() {
    return _cst_new_box_autoadd_permission();
  }

  late final _cst_new_box_autoadd_permissionPtr =
      _lookup<ffi.NativeFunction<ffi.Pointer<wire_cst_permission> Function()>>(
          'frbgen_rdion_runtime_cst_new_box_autoadd_permission');
  late final _cst_new_box_autoadd_permission =
      _cst_new_box_autoadd_permissionPtr
          .asFunction<ffi.Pointer<wire_cst_permission> Function()>();

  ffi.Pointer<wire_cst_setting_ui> cst_new_box_autoadd_setting_ui() {
    return _cst_new_box_autoadd_setting_ui();
  }

  late final _cst_new_box_autoadd_setting_uiPtr =
      _lookup<ffi.NativeFunction<ffi.Pointer<wire_cst_setting_ui> Function()>>(
          'frbgen_rdion_runtime_cst_new_box_autoadd_setting_ui');
  late final _cst_new_box_autoadd_setting_ui =
      _cst_new_box_autoadd_setting_uiPtr
          .asFunction<ffi.Pointer<wire_cst_setting_ui> Function()>();

  ffi.Pointer<wire_cst_settingvalue> cst_new_box_autoadd_settingvalue() {
    return _cst_new_box_autoadd_settingvalue();
  }

  late final _cst_new_box_autoadd_settingvaluePtr = _lookup<
          ffi.NativeFunction<ffi.Pointer<wire_cst_settingvalue> Function()>>(
      'frbgen_rdion_runtime_cst_new_box_autoadd_settingvalue');
  late final _cst_new_box_autoadd_settingvalue =
      _cst_new_box_autoadd_settingvaluePtr
          .asFunction<ffi.Pointer<wire_cst_settingvalue> Function()>();

  ffi.Pointer<
          wire_cst_list_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerExtensionProxy>
      cst_new_list_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerExtensionProxy(
    int len,
  ) {
    return _cst_new_list_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerExtensionProxy(
      len,
    );
  }

  late final _cst_new_list_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerExtensionProxyPtr =
      _lookup<
              ffi.NativeFunction<
                  ffi.Pointer<
                          wire_cst_list_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerExtensionProxy>
                      Function(ffi.Int32)>>(
          'frbgen_rdion_runtime_cst_new_list_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerExtensionProxy');
  late final _cst_new_list_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerExtensionProxy =
      _cst_new_list_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerExtensionProxyPtr
          .asFunction<
              ffi.Pointer<
                      wire_cst_list_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerExtensionProxy>
                  Function(int)>();

  ffi.Pointer<wire_cst_list_String> cst_new_list_String(
    int len,
  ) {
    return _cst_new_list_String(
      len,
    );
  }

  late final _cst_new_list_StringPtr = _lookup<
      ffi.NativeFunction<
          ffi.Pointer<wire_cst_list_String> Function(
              ffi.Int32)>>('frbgen_rdion_runtime_cst_new_list_String');
  late final _cst_new_list_String = _cst_new_list_StringPtr
      .asFunction<ffi.Pointer<wire_cst_list_String> Function(int)>();

  ffi.Pointer<wire_cst_list_entry> cst_new_list_entry(
    int len,
  ) {
    return _cst_new_list_entry(
      len,
    );
  }

  late final _cst_new_list_entryPtr = _lookup<
      ffi.NativeFunction<
          ffi.Pointer<wire_cst_list_entry> Function(
              ffi.Int32)>>('frbgen_rdion_runtime_cst_new_list_entry');
  late final _cst_new_list_entry = _cst_new_list_entryPtr
      .asFunction<ffi.Pointer<wire_cst_list_entry> Function(int)>();

  ffi.Pointer<wire_cst_list_episode> cst_new_list_episode(
    int len,
  ) {
    return _cst_new_list_episode(
      len,
    );
  }

  late final _cst_new_list_episodePtr = _lookup<
      ffi.NativeFunction<
          ffi.Pointer<wire_cst_list_episode> Function(
              ffi.Int32)>>('frbgen_rdion_runtime_cst_new_list_episode');
  late final _cst_new_list_episode = _cst_new_list_episodePtr
      .asFunction<ffi.Pointer<wire_cst_list_episode> Function(int)>();

  ffi.Pointer<wire_cst_list_episode_list> cst_new_list_episode_list(
    int len,
  ) {
    return _cst_new_list_episode_list(
      len,
    );
  }

  late final _cst_new_list_episode_listPtr = _lookup<
      ffi.NativeFunction<
          ffi.Pointer<wire_cst_list_episode_list> Function(
              ffi.Int32)>>('frbgen_rdion_runtime_cst_new_list_episode_list');
  late final _cst_new_list_episode_list = _cst_new_list_episode_listPtr
      .asFunction<ffi.Pointer<wire_cst_list_episode_list> Function(int)>();

  ffi.Pointer<wire_cst_list_image_list_audio> cst_new_list_image_list_audio(
    int len,
  ) {
    return _cst_new_list_image_list_audio(
      len,
    );
  }

  late final _cst_new_list_image_list_audioPtr = _lookup<
          ffi.NativeFunction<
              ffi.Pointer<wire_cst_list_image_list_audio> Function(ffi.Int32)>>(
      'frbgen_rdion_runtime_cst_new_list_image_list_audio');
  late final _cst_new_list_image_list_audio = _cst_new_list_image_list_audioPtr
      .asFunction<ffi.Pointer<wire_cst_list_image_list_audio> Function(int)>();

  ffi.Pointer<wire_cst_list_media_type> cst_new_list_media_type(
    int len,
  ) {
    return _cst_new_list_media_type(
      len,
    );
  }

  late final _cst_new_list_media_typePtr = _lookup<
      ffi.NativeFunction<
          ffi.Pointer<wire_cst_list_media_type> Function(
              ffi.Int32)>>('frbgen_rdion_runtime_cst_new_list_media_type');
  late final _cst_new_list_media_type = _cst_new_list_media_typePtr
      .asFunction<ffi.Pointer<wire_cst_list_media_type> Function(int)>();

  ffi.Pointer<wire_cst_list_permission> cst_new_list_permission(
    int len,
  ) {
    return _cst_new_list_permission(
      len,
    );
  }

  late final _cst_new_list_permissionPtr = _lookup<
      ffi.NativeFunction<
          ffi.Pointer<wire_cst_list_permission> Function(
              ffi.Int32)>>('frbgen_rdion_runtime_cst_new_list_permission');
  late final _cst_new_list_permission = _cst_new_list_permissionPtr
      .asFunction<ffi.Pointer<wire_cst_list_permission> Function(int)>();

  ffi.Pointer<wire_cst_list_prim_u_8_strict> cst_new_list_prim_u_8_strict(
    int len,
  ) {
    return _cst_new_list_prim_u_8_strict(
      len,
    );
  }

  late final _cst_new_list_prim_u_8_strictPtr = _lookup<
      ffi.NativeFunction<
          ffi.Pointer<wire_cst_list_prim_u_8_strict> Function(
              ffi.Int32)>>('frbgen_rdion_runtime_cst_new_list_prim_u_8_strict');
  late final _cst_new_list_prim_u_8_strict = _cst_new_list_prim_u_8_strictPtr
      .asFunction<ffi.Pointer<wire_cst_list_prim_u_8_strict> Function(int)>();

  ffi.Pointer<wire_cst_list_record_string_string>
      cst_new_list_record_string_string(
    int len,
  ) {
    return _cst_new_list_record_string_string(
      len,
    );
  }

  late final _cst_new_list_record_string_stringPtr = _lookup<
          ffi.NativeFunction<
              ffi.Pointer<wire_cst_list_record_string_string> Function(
                  ffi.Int32)>>(
      'frbgen_rdion_runtime_cst_new_list_record_string_string');
  late final _cst_new_list_record_string_string =
      _cst_new_list_record_string_stringPtr.asFunction<
          ffi.Pointer<wire_cst_list_record_string_string> Function(int)>();

  ffi.Pointer<wire_cst_list_subtitles> cst_new_list_subtitles(
    int len,
  ) {
    return _cst_new_list_subtitles(
      len,
    );
  }

  late final _cst_new_list_subtitlesPtr = _lookup<
      ffi.NativeFunction<
          ffi.Pointer<wire_cst_list_subtitles> Function(
              ffi.Int32)>>('frbgen_rdion_runtime_cst_new_list_subtitles');
  late final _cst_new_list_subtitles = _cst_new_list_subtitlesPtr
      .asFunction<ffi.Pointer<wire_cst_list_subtitles> Function(int)>();

  int dummy_method_to_enforce_bundling() {
    return _dummy_method_to_enforce_bundling();
  }

  late final _dummy_method_to_enforce_bundlingPtr =
      _lookup<ffi.NativeFunction<ffi.Int64 Function()>>(
          'dummy_method_to_enforce_bundling');
  late final _dummy_method_to_enforce_bundling =
      _dummy_method_to_enforce_bundlingPtr.asFunction<int Function()>();
}

typedef DartPostCObjectFnType
    = ffi.Pointer<ffi.NativeFunction<DartPostCObjectFnTypeFunction>>;
typedef DartPostCObjectFnTypeFunction = ffi.Bool Function(
    DartPort port_id, ffi.Pointer<ffi.Void> message);
typedef DartDartPostCObjectFnTypeFunction = bool Function(
    DartDartPort port_id, ffi.Pointer<ffi.Void> message);
typedef DartPort = ffi.Int64;
typedef DartDartPort = int;

final class wire_cst_list_prim_u_8_strict extends ffi.Struct {
  external ffi.Pointer<ffi.Uint8> ptr;

  @ffi.Int32()
  external int len;
}

final class wire_cst_Permission_StoragePermission extends ffi.Struct {
  external ffi.Pointer<wire_cst_list_prim_u_8_strict> path;

  @ffi.Bool()
  external bool write;
}

final class PermissionKind extends ffi.Union {
  external wire_cst_Permission_StoragePermission StoragePermission;
}

final class wire_cst_permission extends ffi.Struct {
  @ffi.Int32()
  external int tag;

  external PermissionKind kind;
}

final class wire_cst_Settingvalue_String extends ffi.Struct {
  external ffi.Pointer<wire_cst_list_prim_u_8_strict> val;

  external ffi.Pointer<wire_cst_list_prim_u_8_strict> default_val;
}

final class wire_cst_Settingvalue_Number extends ffi.Struct {
  @ffi.Double()
  external double val;

  @ffi.Double()
  external double default_val;
}

final class wire_cst_Settingvalue_Boolean extends ffi.Struct {
  @ffi.Bool()
  external bool val;

  @ffi.Bool()
  external bool default_val;
}

final class SettingvalueKind extends ffi.Union {
  external wire_cst_Settingvalue_String String;

  external wire_cst_Settingvalue_Number Number;

  external wire_cst_Settingvalue_Boolean Boolean;
}

final class wire_cst_settingvalue extends ffi.Struct {
  @ffi.Int32()
  external int tag;

  external SettingvalueKind kind;
}

final class wire_cst_list_String extends ffi.Struct {
  external ffi.Pointer<ffi.Pointer<wire_cst_list_prim_u_8_strict>> ptr;

  @ffi.Int32()
  external int len;
}

final class wire_cst_DataSource_Paragraphlist extends ffi.Struct {
  external ffi.Pointer<wire_cst_list_String> paragraphs;
}

final class DataSourceKind extends ffi.Union {
  external wire_cst_DataSource_Paragraphlist Paragraphlist;
}

final class wire_cst_data_source extends ffi.Struct {
  @ffi.Int32()
  external int tag;

  external DataSourceKind kind;
}

final class wire_cst_record_string_string extends ffi.Struct {
  external ffi.Pointer<wire_cst_list_prim_u_8_strict> field0;

  external ffi.Pointer<wire_cst_list_prim_u_8_strict> field1;
}

final class wire_cst_list_record_string_string extends ffi.Struct {
  external ffi.Pointer<wire_cst_record_string_string> ptr;

  @ffi.Int32()
  external int len;
}

final class wire_cst_entry extends ffi.Struct {
  external ffi.Pointer<wire_cst_list_prim_u_8_strict> id;

  external ffi.Pointer<wire_cst_list_prim_u_8_strict> url;

  external ffi.Pointer<wire_cst_list_prim_u_8_strict> title;

  @ffi.Int32()
  external int media_type;

  external ffi.Pointer<wire_cst_list_prim_u_8_strict> cover;

  external ffi.Pointer<wire_cst_list_record_string_string> cover_header;

  external ffi.Pointer<wire_cst_list_String> auther;

  external ffi.Pointer<ffi.Float> rating;

  external ffi.Pointer<ffi.Float> views;

  external ffi.Pointer<ffi.Int64> length;
}

final class wire_cst_LinkSource_Epub extends ffi.Struct {
  external ffi.Pointer<wire_cst_list_prim_u_8_strict> link;
}

final class wire_cst_LinkSource_Pdf extends ffi.Struct {
  external ffi.Pointer<wire_cst_list_prim_u_8_strict> link;
}

final class wire_cst_image_list_audio extends ffi.Struct {
  external ffi.Pointer<wire_cst_list_prim_u_8_strict> link;

  @ffi.Int64()
  external int from;

  @ffi.Int64()
  external int to;
}

final class wire_cst_list_image_list_audio extends ffi.Struct {
  external ffi.Pointer<wire_cst_image_list_audio> ptr;

  @ffi.Int32()
  external int len;
}

final class wire_cst_LinkSource_Imagelist extends ffi.Struct {
  external ffi.Pointer<wire_cst_list_String> links;

  external ffi.Pointer<wire_cst_list_record_string_string> header;

  external ffi.Pointer<wire_cst_list_image_list_audio> audio;
}

final class wire_cst_subtitles extends ffi.Struct {
  external ffi.Pointer<wire_cst_list_prim_u_8_strict> title;

  external ffi.Pointer<wire_cst_list_prim_u_8_strict> url;
}

final class wire_cst_list_subtitles extends ffi.Struct {
  external ffi.Pointer<wire_cst_subtitles> ptr;

  @ffi.Int32()
  external int len;
}

final class wire_cst_LinkSource_M3u8 extends ffi.Struct {
  external ffi.Pointer<wire_cst_list_prim_u_8_strict> link;

  external ffi.Pointer<wire_cst_list_subtitles> sub;
}

final class LinkSourceKind extends ffi.Union {
  external wire_cst_LinkSource_Epub Epub;

  external wire_cst_LinkSource_Pdf Pdf;

  external wire_cst_LinkSource_Imagelist Imagelist;

  external wire_cst_LinkSource_M3u8 M3u8;
}

final class wire_cst_link_source extends ffi.Struct {
  @ffi.Int32()
  external int tag;

  external LinkSourceKind kind;
}

final class wire_cst_SettingUI_PathSelection extends ffi.Struct {
  external ffi.Pointer<wire_cst_list_prim_u_8_strict> label;

  @ffi.Bool()
  external bool pickfolder;
}

final class wire_cst_SettingUI_Slider extends ffi.Struct {
  external ffi.Pointer<wire_cst_list_prim_u_8_strict> label;

  @ffi.Double()
  external double min;

  @ffi.Double()
  external double max;

  @ffi.Double()
  external double step;
}

final class wire_cst_SettingUI_Checkbox extends ffi.Struct {
  external ffi.Pointer<wire_cst_list_prim_u_8_strict> label;
}

final class wire_cst_SettingUI_Textbox extends ffi.Struct {
  external ffi.Pointer<wire_cst_list_prim_u_8_strict> label;
}

final class wire_cst_SettingUI_Dropdown extends ffi.Struct {
  external ffi.Pointer<wire_cst_list_prim_u_8_strict> label;

  external ffi.Pointer<wire_cst_list_record_string_string> options;
}

final class SettingUIKind extends ffi.Union {
  external wire_cst_SettingUI_PathSelection PathSelection;

  external wire_cst_SettingUI_Slider Slider;

  external wire_cst_SettingUI_Checkbox Checkbox;

  external wire_cst_SettingUI_Textbox Textbox;

  external wire_cst_SettingUI_Dropdown Dropdown;
}

final class wire_cst_setting_ui extends ffi.Struct {
  @ffi.Int32()
  external int tag;

  external SettingUIKind kind;
}

final class wire_cst_list_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerExtensionProxy
    extends ffi.Struct {
  external ffi.Pointer<ffi.UintPtr> ptr;

  @ffi.Int32()
  external int len;
}

final class wire_cst_list_entry extends ffi.Struct {
  external ffi.Pointer<wire_cst_entry> ptr;

  @ffi.Int32()
  external int len;
}

final class wire_cst_episode extends ffi.Struct {
  external ffi.Pointer<wire_cst_list_prim_u_8_strict> id;

  external ffi.Pointer<wire_cst_list_prim_u_8_strict> name;

  external ffi.Pointer<wire_cst_list_prim_u_8_strict> url;

  external ffi.Pointer<wire_cst_list_prim_u_8_strict> cover;

  external ffi.Pointer<wire_cst_list_record_string_string> cover_header;

  external ffi.Pointer<wire_cst_list_prim_u_8_strict> timestamp;
}

final class wire_cst_list_episode extends ffi.Struct {
  external ffi.Pointer<wire_cst_episode> ptr;

  @ffi.Int32()
  external int len;
}

final class wire_cst_episode_list extends ffi.Struct {
  external ffi.Pointer<wire_cst_list_prim_u_8_strict> title;

  external ffi.Pointer<wire_cst_list_episode> episodes;
}

final class wire_cst_list_episode_list extends ffi.Struct {
  external ffi.Pointer<wire_cst_episode_list> ptr;

  @ffi.Int32()
  external int len;
}

final class wire_cst_list_media_type extends ffi.Struct {
  external ffi.Pointer<ffi.Int32> ptr;

  @ffi.Int32()
  external int len;
}

final class wire_cst_list_permission extends ffi.Struct {
  external ffi.Pointer<wire_cst_permission> ptr;

  @ffi.Int32()
  external int len;
}

final class wire_cst_entry_detailed extends ffi.Struct {
  external ffi.Pointer<wire_cst_list_prim_u_8_strict> id;

  external ffi.Pointer<wire_cst_list_prim_u_8_strict> url;

  external ffi.Pointer<wire_cst_list_prim_u_8_strict> title;

  @ffi.Int32()
  external int media_type;

  @ffi.Int32()
  external int status;

  external ffi.Pointer<wire_cst_list_prim_u_8_strict> cover;

  external ffi.Pointer<wire_cst_list_record_string_string> cover_header;

  external ffi.Pointer<wire_cst_list_episode_list> episodes;

  external ffi.Pointer<wire_cst_list_String> genres;

  external ffi.Pointer<wire_cst_list_String> alttitles;

  external ffi.Pointer<wire_cst_list_String> auther;

  external ffi.Pointer<ffi.Float> rating;

  external ffi.Pointer<ffi.Float> views;

  external ffi.Pointer<ffi.Int64> length;
}

final class wire_cst_extension_data extends ffi.Struct {
  external ffi.Pointer<wire_cst_list_prim_u_8_strict> id;

  external ffi.Pointer<wire_cst_list_prim_u_8_strict> repo;

  external ffi.Pointer<wire_cst_list_prim_u_8_strict> name;

  external ffi.Pointer<wire_cst_list_media_type> media_type;

  external ffi.Pointer<wire_cst_list_prim_u_8_strict> giturl;

  external ffi.Pointer<wire_cst_list_prim_u_8_strict> version;

  external ffi.Pointer<wire_cst_list_prim_u_8_strict> desc;

  external ffi.Pointer<wire_cst_list_prim_u_8_strict> author;

  external ffi.Pointer<wire_cst_list_prim_u_8_strict> license;

  external ffi.Pointer<wire_cst_list_String> tags;

  external ffi.Pointer<ffi.Bool> nsfw;

  external ffi.Pointer<wire_cst_list_String> lang;

  external ffi.Pointer<wire_cst_list_prim_u_8_strict> url;

  external ffi.Pointer<wire_cst_list_prim_u_8_strict> icon;
}

final class wire_cst_permission_request extends ffi.Struct {
  external wire_cst_permission permission;

  external ffi.Pointer<wire_cst_list_prim_u_8_strict> msg;
}

final class wire_cst_setting extends ffi.Struct {
  external wire_cst_settingvalue val;

  @ffi.Int32()
  external int settingtype;

  external ffi.Pointer<wire_cst_setting_ui> ui;
}

final class wire_cst_Source_Data extends ffi.Struct {
  external ffi.Pointer<wire_cst_data_source> sourcedata;
}

final class wire_cst_Source_Directlink extends ffi.Struct {
  external ffi.Pointer<wire_cst_link_source> sourcedata;
}

final class SourceKind extends ffi.Union {
  external wire_cst_Source_Data Data;

  external wire_cst_Source_Directlink Directlink;
}

final class wire_cst_source extends ffi.Struct {
  @ffi.Int32()
  external int tag;

  external SourceKind kind;
}
